const options = [
    {title:'خانه هوشمند',id:'1',url:'https://img.icons8.com/fluency/48/smart-home-connection.png'},
    {title:'سیستم سرمایش',id:'2',url:'https://img.icons8.com/color/48/fan.png'},
    {title:'درب برقی',id:'3',url:'https://img.icons8.com/color-glass/48/garage-door.png'},
    {title:'باربیکیو',id:'4',url:'https://img.icons8.com/color/48/grill.png'},
    {title:'استخر',id:'5',url:'https://img.icons8.com/color/48/swimming-pool.png'},
    {title:'پارکینگ',id:'6',url:'https://img.icons8.com/fluency/48/parking.png'},
    {title:'کف پوش',id:'7',url:'https://img.icons8.com/cotton/64/wooden-floor.png'},
    {title:'آسانسور',id:'8',url:'https://img.icons8.com/external-flaticons-flat-flat-icons/64/external-elevator-wayfinding-flaticons-flat-flat-icons.png'},
    {title:'لابی',id:'9',url:'https://img.icons8.com/color/48/waiting-room.png'},
    {title:'نگهبان',id:'10',url:'https://img.icons8.com/color/48/security-guard.png'},
    {title:'بالکن',id:'11',url:'https://img.icons8.com/fluency/48/balcony.png'},
    {title:'دوربین حفاظتی',id:'12',url:'https://img.icons8.com/color/48/ptz-camera.png'},
    {title:'سیستم گرمایش',id:'13',url:'https://img.icons8.com/fluency/48/heating-radiator.png'},
    {title:'کابینت MDF',id:'14',url:'https://img.icons8.com/external-smashingstocks-flat-smashing-stocks/66/external-Cabinets-interior-smashingstocks-flat-smashing-stocks-6.png'},
    {title:'دسترسی به بیمارستان',id:'15',url:'https://img.icons8.com/emoji/48/hospital-emoji.png'},
    {title:'دسترسی به فروشگاه',id:'16',url:'https://img.icons8.com/color/48/shop.png'},
    {title:'دسترسی به آتشنشانی',id:'17',url:'https://img.icons8.com/emoji/48/fire-engine.png'},
    {title:'دسترسی به مدرسه',id:'18',url:'https://img.icons8.com/fluency/48/school.png'},
    {title:'دسترسی به نانوایی',id:'19',url:'https://img.icons8.com/external-itim2101-flat-itim2101/64/external-bakery-store-itim2101-flat-itim2101.png'},
    {title:'دسترسی به حمل و نقل عمومی',id:'20',url:'https://img.icons8.com/color/48/ground-transportation.png'},
    {title:'دسترسی به آرایشگاه',id:'21',url:'https://img.icons8.com/color/48/barbershop.png'},
]

export default options